version: '3.9'

services:
  taller_backend:
    container_name: taller
    image: taller:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_URL=jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    depends_on:
      - taller_db
  taller_db:
    container_name: taller_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
